### ISSUE TITLE
Add logging before/after bsp.sync, memory after bsp.sync

### ISSUE THREAD

**Issue by simmhan** [dream-lab/goffish_v3#21]
Hama's bsp.sync actually transmits the messages. Having the memory before/after sync allows us to estimate the memory used on the output message buffer. Having the time before/after gives the communiction duration as well.

**Comment by dipkakwani** [comment]
https://github.com/dream-lab/goffish_v3/commit/143287c4798c257baa1804c82d22ace7089f0ffb
